### ISSUE TITLE
Empty VM Template List leads to error pop-up window

### ISSUE THREAD

**Issue by meichenberger** [stepping-stone/vm-manager#73]
When the "Virtual Machine -> VM Templates" menu is clicked and no VM Templates exist yet, a pop-up window with the following message appears:
```
/var/www/localhost/htdocs/vm-manager/protected/controllers/VmTemplateController.php(1885): CPhpLibvirt Vm '' not found!
```
This behaviour is wrong and can not be reproduced under the "Virtual Machine -> Persistent VMs",  "Virtual Machine -> Dynamic VMs" or  "Virtual Machine -> Profiles" menu.

**Comment by flinx27** [comment]
Is there a possibility to see this on a live system?

**Comment by meichenberger** [comment]
You'll receive the necessary information in a few minutes off list.
